### ISSUE TITLE
Help in running GG experiments

### ISSUE THREAD

**Issue by prateeky2806** [RAIVNLab/supsup#20]
Hi authors, I really enjoyed reading the paper and found it really interesting. I had a few questions about issue I was facing while trying to use your code and replicating the results. 

1. When I am trying to run the GG experiments using the command
`python main.py --config=experiments/GG/splitcifar100/configs/rn18-supsup.yaml --name=id=test_gg --sparsity=1 --seed=0 --log-dir=runs/rn18-supsup --epochs=2 --data=./data`
I am getting an error saying 
```
File "./supsup/adaptors.py", line 59, in gt
    alphas[task] = 1
RuntimeError: a view of a leaf Variable that requires grad is being used in an in-place operation.
```

2. I was trying to run the code in a multigpu setting using the command, 
`python main.py --config=experiments/GG/splitcifar100/configs/rn18-supsup.yaml --name=id=test_gg --sparsity=1 --seed=0 --log-dir=runs/rn18-supsup --epochs=100 --data=./data --multigpu=0,1`
While doing so I am getting an error 
```
IndexError: index 0 is out of range
File "/playpen2/home/prateek/projects/cl/cl_project/models/modules.py", line 86, in forward
    subnet = module_util.GetSubnet.apply( self.scores[self.task].abs(), self.sparsity )
```
I tried to debug the code and it seems like during the multrigpu training, the self.scores parameter list is initialized correctly but becomes an empty list by the time forward pass is called. Can you help me with this? 

3. What's the use case of task_eval parameter? 
4. Storing these masks for each task is almost the same number of parameters as the model. Can this be implemented in a different manner to save memory on gpu in order to have bigger models, any suggestions for this? I was also wondering how to go about storing the masks as attractors in a Hopfield Network.

**Comment by vkramanuj** [comment]
(1 and 2) Thank you for bringing these issues to our attention. We found that the way `ParameterList` objects are copied across GPUs with DataParallel is inconsistent for different pytorch versions (see [https://github.com/pytorch/pytorch/issues/36035](https://github.com/pytorch/pytorch/issues/36035)). There are three options: 1. Use the pytorch version that we recommend (see `requirements.txt`), 2. Run with 1 GPU (`--multigpu 0`) or 3. Modify the code to pass "scores" during the forward pass (this fix will work for all pytorch versions). Your first bug does not occur when running on GPU, which leads me to believe that its an inconsistency with how gradients are computed with pytorch's side. Let me know if 1. or 2. fails to solve your problem. Unfortunately we do not have the bandwidth to implement 3. in the near future, but it's on our to-do list.

(3) The `--task-eval` parameter bypasses the adaptors and just evaluates our mask on each individual task. This should be enough for the `GG` scenario but not the rest, which require adaptors. 

(4) @mitchellnw might have tips for your last question. You could store the masks themselves (not the scores) with lower precision, which is supported in more recent versions of pytorch. This would not work during training, only during inference.

**Comment by mitchellnw** [comment]
Hi @prateeky2806, the experiment config for the HopSupSup experiment is https://github.com/RAIVNLab/supsup/blob/master/experiments/GNu/SplitMNIST/hopsupsup.py.

Hope this helps!

**Comment by prateeky2806** [comment]
Thanks, @vkramanuj and @mitchellnw, I will try to follow the options you have provided and will try to fix these issues!
