### ISSUE TITLE
Why output size of 100 for mnist notebook

### ISSUE THREAD

**Issue by jamesrichter** [RAIVNLab/supsup#5]
I'm going through the MNIST notebook.  The output layer size for the mnist notebook looks like it's 100 and I'm wondering if there's a reason for this, seems like it should be 10.

**Comment by mitchellnw** [comment]
Yes, if you change it to 10 you'll find it will not work :)

Check out sec 3.6 and G in the paper for more explanation about these "superfluous neurons".
