### ISSUE TITLE
Error when running split cifar100 with supsup-transfer

### ISSUE THREAD

**Issue by IsaacRe** [RAIVNLab/supsup#7]
Hello all,

When running split cifar100 with `rn18-supsup-transfer.yaml` as the config I run into the following error:

`Traceback (most recent call last):`
`  File "main.py", line 420, in <module>`
`    main()`
`  File "main.py", line 256, in main`
`    data_loader,`
`  File "/nethome/irehg6/phase2/baselines/supsup/trainers/reinit.py", line 104, in train`
`    / m.scores[:task_idx].norm()`
`  File "/nethome/irehg6/miniconda3/envs/bl-env/lib/python3.7/site-packages/torch/nn/modules/module.py", line 594, in` `__getattr__`
`    type(self).__name__, name))`
`AttributeError: 'ParameterList' object has no attribute 'norm'`

The exact command run from the project root is
`python main.py \`
`--config=experiments/GG/splitcifar100/configs/rn18-supsup-transfer.yaml \`
`--name=id=supsup-transfer~seed=0~sparsity=1 \`
`--sparsity=1 \`
`--seed=0 \`
`--log-dir=runs/debug \`
`--epochs=1 \`
`--reinit-adapt=running_mean \`
`--data=~/data \`
`--multigpu=0 \`
`--workers=4 \`

which is copied from the command string generated by `experiments/GG/splitcifar100/rn18-supsup-transfer.py` .

The issue seems to be due to the referenced lines (102-105 in supsup/trainers/reinit.py).
Specifically line 104 `norm()` is called on a `torch.nn.ParameterList` object:
`m.scores[:task_idx].norm()`
Is `m.scores` intended to reference a `ParameterList` here? Shouldn't we instead be using the cached `m.stacked` tensor instead?

I tried changing line 104 to `m.stacked[:task_idx].norm()` and the error goes away.

I then, however get a new error:

`Traceback (most recent call last):`
`  File "main.py", line 420, in <module>`
`    main()`
`  File "main.py", line 256, in main`
`    data_loader,`
`  File "/nethome/irehg6/phase2/baselines/supsup/trainers/reinit.py", line 120, in train`
`    output = model(data)`
`  File "/nethome/irehg6/miniconda3/envs/bl-env/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__`
`    result = self.forward(*input, **kwargs)`
`  File "/nethome/irehg6/miniconda3/envs/bl-env/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 153, in forward`
`    return self.module(*inputs[0], **kwargs[0])`
`  File "/nethome/irehg6/miniconda3/envs/bl-env/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__`
`    result = self.forward(*input, **kwargs)`
`  File "/nethome/irehg6/phase2/baselines/supsup/models/gemresnet.py", line 68, in forward`
`    out = relu(self.bn1(self.conv1(x.view(bsz, 3, 32, 32))))`
`  File "/nethome/irehg6/miniconda3/envs/bl-env/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__`
`    result = self.forward(*input, **kwargs)`
`  File "/nethome/irehg6/phase2/baselines/supsup/models/modules.py", line 95, in forward`
`    x, w, self.bias, self.stride, self.padding, self.dilation, self.groups`
`RuntimeError: expected stride to be a single integer value or a list of 3 values to match the convolution dimensions, but got stride=[1, 1]`

It seems to again be an issue with the lines 102-105. In the lines we now assign `m.stacked[:task_idx].clone() / m.stacked[:task_idx].norm()` to `m.scores[task_idx].data` . But since `m.stacked[:task_idx]` has dimensionality (task_idx X out_channels X in_channels X filter_width X filter_height), `m.scores[task_idx]` assumes this dimensionality after being reinitialized. Later when the scores are used to generate a mask that is applied to the filter weight this has the effect of causing the filter weight to assume this dimensionality as well (and seems to cause PyTorch to think the filter is that of a 3D convolution?).

In any case it seems like what you want to do is average across the first task_idx score tensors in the stacked sequence, correct? In this case shouldn't  line 103 look something like `m.stacked[:task_idx].mean(dim=0)` ?

I went ahead and made both of these changes so that lines 102-105 are
`m.scores[task_idx].data = (`
                            `m.stacked[:task_idx].mean(dim=0)`
                            `/ m.stacked[:task_idx].norm()`
                        `)`

With these changes I got the experiment to run. I just wanted to run them by you all to see if this is, in fact, a bug, or if I'm just missing something / dont have the repo set up properly.

Also, great work on the paper! And thank you for publishing a well-organized, legible codebase :)

**Comment by IsaacRe** [comment]
Update:
The final accuracies for all tasks following task 0 end up being around 20%, with the above fixes, so those changes must not be correct.

**Comment by mitchellnw** [comment]
thanks for raising this issue, we're on it and will keep you updated

**Comment by vkramanuj** [comment]
Thanks for bringing up this issue. This seems to have been an old bug from when we migrated to a public repo, I'm unsure how it appeared. I have added the fix and retested the code. The issue with your change:

```
m.scores[task_idx].data = (
    m.stacked[:task_idx].mean(dim=0)
        / m.stacked[:task_idx].norm()
)
```

Is that the final tensor has greater norm (by orders of magnitude) than the scores tensor with random initialization (see https://arxiv.org/abs/1911.13299 for mask initialization details). The code should work with the same command now. Please let me know if you have any questions!
