### ISSUE TITLE
GNu scenario for CIFAR10 without hopfield

### ISSUE THREAD

**Issue by rahulvigneswaran** [RAIVNLab/supsup#9]
Hi @vkramanuj , 
Thanks for the awesome paper and repo. Can you let me know the config file for `GNu` scenario for `SplitCIFAR10` without hopfield?

**Comment by rahulvigneswaran** [comment]
I tried to adapt the below code from `experiments/GNu/SplitMNIST/hopsupsup.py` in a crude way. Let me know if this achieves the setup I requested or if I am missing something.
```
import sys, os
sys.path.append(os.path.abspath('.'))
from main import main as run
from args import args
import numpy as np

def main():
    args.set = 'PartitionCIFAR10' #'PartitionMNISTV2'
    args.num_tasks = 5
    args.multigpu = [1]
    args.model = 'GEMResNet18' #'BNNet'
    args.conv_type = 'FastMultitaskMaskConv' #'StandardConv'
    args.bn_type = 'NonAffineNoStatsBN' #'FastHopMaskBN'
    args.conv_init = 'signed_constant'
    # args.adaptor = 'hopfield_recovery'
    args.gamma = 1.5e-3
    args.batch_size = 128
    args.test_batch_size = 64
    args.epochs = 10
    args.adapt = True
    args.output_size = 10
    args.eval_ckpts = []

    args.er_sparsity = True
    args.sparsity = 2

    args.name = 'id=nohopsupup' #'id=hopsupsup'

    args.data = '~/data'
    args.log_dir = "~/checkpoints/test"

    run()

if __name__ == '__main__':
    main()
```

If the above setup is correct, is there any way I can improve the results? These are the results I get out of it,

```
Testing 0: PartitionCIFAR10 (0)

Test set: Accuracy: (0.8955%)

Testing 1: PartitionCIFAR10 (1)

Test set: Accuracy: (0.7995%)

Testing 2: PartitionCIFAR10 (2)

Test set: Accuracy: (0.8500%)

Testing 3: PartitionCIFAR10 (3)

Test set: Accuracy: (0.9365%)

Testing 4: PartitionCIFAR10 (4)

Test set: Accuracy: (0.9170%)
```

**Comment by vkramanuj** [comment]
We currently don't have GNu working in general (e.g. for convnets) for the CIFAR dataset. We do have a config for Split CIFAR with a fully connected network which we will be adding in the next week or so. To answer your question though, the parameter to change to move between the GG and GNu scenarios is `args.adaptor`. `gt` (ground-truth adaptation) corresponds to the GG scenario and `se_oneshot_g_minimization` corresponds to the oneshot algorithm in the GNu scenario. We will add documentation on this in the future.

@mitchellnw do you have anything to add?

**Comment by mitchellnw** [comment]
Nope lgtm thanks Vivek & Rahul

**Comment by rahulvigneswaran** [comment]
Looking forward to the Split CIFAR config. Thanks a lot.
